import { createTheme } from '@mui/material';
const theme = createTheme();
// eslint-disable-next-line import/no-anonymous-default-export
export default {
  BannerBox: {
    width: '100%',
    position: 'relative',
    height: '584px',
    borderRadius: '12px',
    overflow: 'hidden',
    [theme.breakpoints.down('md')]: {
      height: '162px',
    },
  },
  BannerImg: {
    width: '100%',
    position: 'unset',
    borderRadius: '12px',
    overflow: 'hidden',
    '& img': {
      height: 'unset',
      position: 'relative !important',
      objectFit: 'cover',
    },
    [theme.breakpoints.down('md')]: {
      height: '162px',
    },
  },
  BannerContent: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: '#FFFFFF66',
    background:
      'linear-gradient(180deg, rgba(255, 255, 255, 0.581) 62.5%, rgba(255, 255, 255, 0) 100%)',
    top: 0,
    left: 0,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  BannerInnerContentTypoOne: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'Inter',
    fontFtyle: 'normal',
    fontWeight: '700',
    fontSize: '42px',
    lineHeight: '52px',
    [theme.breakpoints.down('md')]: {
      fontSize: '16px',
      lineHeight: '25px',
    },
  },
  BannerInnerContentTypoTwo: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '231px',
    height: '59px',
    background: '#DE0B0B',
    borderRadius: '12px',
    fontFamily: 'Inter',
    fontFtyle: 'normal',
    fontWeight: '700',
    fontSize: '42px',
    lineHeight: '52px',
    color: '#fff',
    [theme.breakpoints.down('md')]: {
      fontSize: '16px',
      lineHeight: '25px',
      width: '110.79px',
      height: '28.3px',
    },
  },
  AboutUsContainerGrid: {
    marginTop: '153px',
    px: '124px',
    [theme.breakpoints.down('md')]: {
      marginTop: 0,
      px: 0,
    },
  },
  AboutUstypoOne: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '40px',
    lineHeight: '26px',
    color: '#DE0B0B',
    [theme.breakpoints.down('md')]: {
      fontFamily: 'Inter',
      fontStyle: 'normal',
      fontWeight: 600,
      fontSize: '16px',
      lineHeight: '26px',
    },
  },
  AboutUstypoTwo: {
    marginTop: '38px',
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '28px',
    textAlign: 'justify',
    color: '#777777',
    [theme.breakpoints.down('md')]: {
      fontFamily: 'Inter',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: '16px',
      lineHeight: '28px',
      marginTop: '4px',
    },
  },
  ChooseUsMobileTypo: {
    marginTop: '38px',
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '28px',
    textAlign: 'justify',
    color: '#777777',
    marginBottom: '32px',
    [theme.breakpoints.down('md')]: {
      fontFamily: 'Inter',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: '16px',
      lineHeight: '28px',
      marginTop: '14px',
    },
    [theme.breakpoints.up('sm')]: {
      display: 'none',
    },
  },
  AboutUstypoThree: {
    marginTop: '96px',
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '28px',
    textAlign: 'justify',
    color: '#777777',
    [theme.breakpoints.down('md')]: {
      marginTop: '40px',
      fontFamily: 'Inter',
      fontStyle: 'normal',
      fontWeight: 400,
      fontSize: '16px',
      lineHeight: '28px',
    },
  },
  AboutUsGridImg: {
    width: '482px',
    height: '526px',
    borderRadius: '12px',
    overflow: 'hidden',
    '& img': {
      width: '100%',
      height: 'unset',
      position: 'relative !important',
      objectFit: 'cover',
    },
    [theme.breakpoints.down('md')]: {
      width: '100%',
      height: '358px',
      borderRadius: '8.16598px',
      overflow: 'hidden',
    },
  },
  ChooseUsGrid: {
    marginTop: '80px',
    px: '60px',
    [theme.breakpoints.down('md')]: {
      px: 0,
      marginTop: 0,
    },
  },
  ChooseUsGridImg: {
    width: '100%',
    overflow: 'hidden',
    '& img': {
      width: '100%',
      height: 'unset',
      position: 'relative !important',
      objectFit: 'cover',
    },
    [theme.breakpoints.down('md')]: {
      width: '100%',
      overflow: 'hidden',
    },
  },
  ChooseUsContentBox: {
    display: 'flex',
    gap: '24px',
    justifyContent: 'flex-end',
    marginBottom: '54px',
    marginTop: '70px',
    [theme.breakpoints.down('md')]: {
      justifyContent: 'flex-start',
      alignItems: 'center',
      marginBottom: 0,
      marginTop: 0,
    },
  },
  ChooseUsContentBoxTypo: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '40px',
    lineHeight: '26px',
    color: '#DE0B0B',
    [theme.breakpoints.down('md')]: {
      fontWeight: 600,
      fontSize: '16px',
    },
  },
  ChooseUsContentInnerBox: {
    width: '27.66px',
    height: '27.66px',
    background: '#DE0B0B',
    borderRadius: '100%',
    [theme.breakpoints.down('md')]: {
      width: '13.66px',
      height: '13.66px',
    },
  },
  ChooseUsContentInnerBoxIcon: {
    display: 'flex',
  },
  ChooseUsIcon: {
    width: '30.66px',
    height: '30.66px',
    color: '#DE0B0B',
    marginLeft: '-16px',
    [theme.breakpoints.down('md')]: {
      width: '16.66px',
      height: '16.66px',
      marginLeft: '-8px',
    },
  },
  ChooseusCardStack: {
    flexDirection: 'row',
    gap: '18px',
    marginBottom: '32px',
    [theme.breakpoints.down('md')]: {
      flexDirection: 'column',
    },
  },
  ChooseUsCardBox: {
    minWidth: '64px',
    width: '64px',
    height: '64px',
    background: '#141414',
    borderRadius: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    [theme.breakpoints.down('md')]: {
      minWidth: '32px',
      width: '32px',
      height: '32px',
    },
  },
  ChooseUsCardIcon: {
    fontSize: '30px',
    color: '#fff',
    [theme.breakpoints.down('md')]: {
      fontSize: '15px',
    },
  },
  ChooseUsCardTypoOne: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '20px',
    lineHeight: '26px',
    color: '#141414',
    [theme.breakpoints.down('md')]: {
      fontSize: '16px',
    },
  },
  ChooseUsCardTypoTwo: {
    marginTop: '12px',
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '28px',
    color: '#777777',
    [theme.breakpoints.down('md')]: {
      fontSize: '16px',
    },
  },
  OurTeamGrid: {
    marginTop: '50px',
    alignItems: 'center',
    [theme.breakpoints.down('md')]: {
      marginTop: 0,
    },
  },
  OurTeamBox: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '20px',
    [theme.breakpoints.down('md')]: {
      gap: '8px',
      justifyContent: 'flex-start',
    },
  },
  OurTeamImg: {
    width: '118.95px',
    height: '118.95px',
    overflow: 'hidden',
    '& img': {
      width: '100%',
      height: 'unset',
      position: 'relative !important',
      objectFit: 'cover',
    },
    [theme.breakpoints.down('md')]: {
      width: '33.95px',
      height: '33.95px',
    },
  },
  OurTeamTypoMain: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '42px',
    lineHeight: '52px',
    color: '#DE0B0B',
    [theme.breakpoints.down('md')]: {
      fontWeight: 600,
      fontSize: '16px',
    },
  },
  OurTeamSectionTwo: {
    position: 'relative',
    width: '100%',
    height: '453.26px',
    [theme.breakpoints.down('md')]: {
      height: '217.87px',
      marginBottom: '20px',
      marginTop: '20px',
    },
  },
  OurTeamSectionTwoImgOne: {
    width: '162.38px',
    height: '162.38px',
    borderRadius: '100%',
    position: 'absolute',
    top: '20.84px',
    left: 0,
    overflow: 'hidden',
    '& img': {
      width: '100%',
      height: 'unset',
      position: 'relative !important',
      objectFit: 'cover',
    },
    [theme.breakpoints.down('md')]: {
      width: '78.05px',
      height: '78.05px',
    },
  },
  OutTeamResearch: {
    width: '134.26px',
    height: '134.26px',
    borderRadius: '100%',
    background: '#DE0B0B',
    border: '7.15985px solid #D6D6D6',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: '25px',
    bottom: '89px',
    [theme.breakpoints.down('md')]: {
      width: '64.54px',
      height: '64.54px',
      border: '3.44156px solid #D6D6D6',
      left: '12px',
      bottom: '35px',
    },
  },
  OurTeamTypo: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: '20px',
    color: '#FFFFFF',
    textAlign: 'center',
    [theme.breakpoints.down('md')]: {
      fontSize: '7.69079px',
      lineHeight: '10px',
    },
  },
  OutTeamCEO: {
    width: '75.01px',
    height: '75.01px',
    borderRadius: '100%',
    background: '#DE0B0B',
    border: '7.15985px solid #D6D6D6',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: '219px',
    top: 0,
    [theme.breakpoints.down('md')]: {
      width: '36.05px',
      height: '36.05px',
      border: '1.9227px solid #D6D6D6',
      left: '105px',
      top: 0,
    },
  },
  OurTeamSectionTwoImgTwo: {
    width: '192.88px',
    height: '192.88px',
    borderRadius: '100%',
    position: 'absolute',
    top: '94.2px',
    left: '174px',
    overflow: 'hidden',
    // '& img': {
    //   width: '100%',
    //   height: 'unset',
    //   position: 'relative !important',
    //   objectFit: 'cover',
    // },
    [theme.breakpoints.down('md')]: {
      width: '92.71px',
      height: '92.71px',
      position: 'absolute',
      top: '50px',
      left: '83px',
    },
  },
  OutTeamScientist: {
    width: '134.26px',
    height: '134.26px',
    borderRadius: '100%',
    background: '#DE0B0B',
    border: '7.15985px solid #D6D6D6',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: '218px',
    bottom: 0,
    [theme.breakpoints.down('md')]: {
      width: '64.54px',
      height: '64.54px',
      position: 'absolute',
      left: '105px',
      bottom: 0,
      border: '3.44156px solid #D6D6D6',
    },
  },
  OurTeamSectionTwoImgThree: {
    width: '112.92px',
    height: '112.92px',
    borderRadius: '100%',
    position: 'absolute',
    bottom: '99.42px',
    right: '192.16px',
    overflow: 'hidden',
    // '& img': {
    //   width: '100%',
    //   height: 'unset',
    //   position: 'relative !important',
    //   objectFit: 'cover',
    // },
    [theme.breakpoints.down('md')]: {
      width: '54.28px',
      height: '54.28px',
      position: 'absolute',
      bottom: '37.80px',
      right: '70.75px',
    },
  },
  OurTeamSectionTwoImgFour: {
    width: '161.55px',
    height: '161.55px',
    borderRadius: '100%',
    position: 'absolute',
    top: '13.42px',
    right: '194.02px',
    overflow: 'hidden',
    // '& img': {
    //   width: '100%',
    //   height: 'unset',
    //   position: 'relative !important',
    //   objectFit: 'cover',
    // },
    [theme.breakpoints.down('md')]: {
      width: '70.66px',
      height: '70.66px',
      position: 'absolute',
      top: '6.42px',
      right: '73px',
    },
  },
  OurTeamSectionTwoImgFive: {
    width: '117.87px',
    height: '117.87px',
    borderRadius: '100%',
    position: 'absolute',
    bottom: '166.19px',
    right: '56.87px',
    overflow: 'hidden',
    // '& img': {
    //   width: '100%',
    //   height: 'unset',
    //   position: 'relative !important',
    //   objectFit: 'cover',
    // },
    [theme.breakpoints.down('md')]: {
      width: '56.66px',
      height: '56.66px',
      position: 'absolute',
      bottom: '80px',
      right: '22px',
    },
  },
  OurTeamModel: {
    width: '134.26px',
    height: '134.26px',
    borderRadius: '100%',
    background: '#DE0B0B',
    border: '7.15985px solid #D6D6D6',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 0,
    bottotop: '9px',
    [theme.breakpoints.down('md')]: {
      width: '64.54px',
      height: '64.54px',
      border: '3.44156px solid #D6D6D6',
      right: 0,
      bottotop: '9px',
    },
  },
};
