import { SessionProvider } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import { ComponentType } from 'react';
import DefaultLayout from '@/components/layouts/DefaultLayout';

import '@src/styles/main.scss';
// import all styles

type AppProps = {
  Component: ComponentType<any>;
  pageProps: { session: any; [key: string]: any };
};

export default function App({ Component, pageProps: { session, ...pageProps } }: AppProps) {
  return (
    // `session` comes from `getServerSideProps` or `getInitialProps`.
    // Avoids flickering/session loading on first load.
    <>
      <Head>
        <title>SynapMe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={session} refetchInterval={5 * 60}>
        <Component {...pageProps} />
      </SessionProvider>
    </>
  );
}
